apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-wedding
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: wedding-container
          image: sanjay145/wedding
          ports:
            - containerPort: 80
