apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx
        ports:
          - containerPort: 80
